Count button
Janna135/impactapp pull request #2
Opened 2018-06-05 10:45 UTC by Janna135

2018-06-05 10:53 UTC, IanCapo reviewed
Schaut gut aus

2018-06-06 05:53 UTC, badabam requested changes
Sind nur Kleinigkeiten, bitte verbessern. Fragen gerne zu mir.

2018-06-06 05:53 UTC, badabam commented on src/App.js
>  injectGlobal(`
Das würde ich in eine Datei auslagern oder als .css-Datei schreiben.

2018-06-06 05:53 UTC, badabam commented on src/App.js
> +  decreaseCount(id) {
Diese Funktion ist fast gleich mit der anderen. Kannst du abstrahieren, wie in meinem Beispielprojekt.

2018-06-06 05:53 UTC, badabam commented on src/components/CountButton.js
> +const StyledButton = styled('div')`
In eigene Datei?

2018-06-06 05:53 UTC, badabam commented on src/components/CountButton.js
> +const SideButton = styled('div')`
In eigene Datei?

2018-06-06 10:07 UTC, badabam approved these changes
Hab nur eine ganz kleine Kleinigkeit gefunden. Bitte anpassen und dann kannst du die Story QAen und mir den Review-Link schicken.

2018-06-06 10:07 UTC, badabam commented on src/components/CountButton.js
> +        <span>
Das `span` macht hier nichts. Bitte weglassen.

2018-06-06 11:01 UTC, merged